### ISSUE TITLE
Showing name 'State' error

### ISSUE THREAD

**Issue by pkinani** [odonnell31/Turtle-Trading-Simulator#1]
I am getting following error. Please look into it if possible.

Traceback (most recent call last):
  File "C:\pythonProject\simulator.py", line 364, in <module>
    trend_trader_simulator(stock=stock,
  File "C:\pythonProject\simulator.py", line 291, in trend_trader_simulator
    TT_financial_state = create_state_object(investment_dollars, entry_signal, exit_signal)
  File "C:\pythonProject\simulator.py", line 102, in create_state_object
    financial_state = State(dollars=dollars,
NameError: name 'State' is not defined
----------------------------------------------------------
The problem got rectified by importing Modsimpy package along with its dependent packages.

**Comment by pkinani** [comment]
The Simulator appears to consider trades only for upward trends for the stock. (It may not be simulating down trending cycle of stock where trade is initiated by shorting and exited by buying at lower price.) In most stocks steep losses were presented by the simulator when stock was down-trending, profits where shown only when stock was up-trending. Michael to confirm my doubt.
